//audience map + EVENT_CATEGORIES array

export const targetAudienceMap: Record<string, string[]> = {
  "Music Concerts": [
    "Teenagers (15–19)",
    "Young Adults (20–30)",
    "Music Enthusiasts",
    "Nightlife Crowd",
    "General Public",
  ],
  "Festivals & Cultural Events": [
    "General Public",
    "Families",
    "Tourists & Expats",
    "Cultural Enthusiasts",
    "Students",
  ],
  "DJ / Club Events": [
    "Young Adults (18–30)",
    "Party Goers",
    "Nightlife Audience",
    "Music Enthusiasts",
  ],
  "Live Performances / Shows": [
    "General Audience",
    "Families",
    "Art & Culture Lovers",
    "Young Adults (20–30)",
  ],
  Conferences: [
    "Corporate Professionals",
    "Business Owners",
    "Industry Experts",
    "Investors",
    "Entrepreneurs",
  ],
  "Seminars / Workshops": [
    "Students",
    "Professionals",
    "Skill Learners",
    "Young Professionals (25–35)",
    "Entrepreneurs",
  ],
  "Product Launches": [
    "Existing Customers",
    "Media & Press",
    "Investors",
    "Tech Enthusiasts",
    "General Public",
  ],
  "Corporate Events / Meetings": [
    "Employees",
    "Executives & Management",
    "Stakeholders",
    "Business Partners",
  ],
  "University Events": [
    "University Students",
    "Lecturers & Academic Staff",
    "School Leavers (A/L Students)",
    "Parents",
  ],
  "Hackathons / Competitions": [
    "Developers & Engineers",
    "University Students",
    "Tech Enthusiasts",
    "Entrepreneurs",
    "Designers",
  ],
  "Training Sessions": [
    "Employees",
    "Students",
    "Skill Learners",
    "Professionals",
    "Young Professionals (25–35)",
  ],
  Weddings: [
    "Families",
    "Friends & Relatives",
    "Wedding Guests",
    "Couples (Planning Stage)",
  ],
  "Birthday Parties": [
    "Friends & Family",
    "Kids (Under 12)",
    "Teenagers (13–18)",
    "Adults (18+)",
  ],
  Anniversaries: ["Couples", "Families", "Close Friends"],
  Reunions: ["Friends", "Alumni Groups", "Families", "Former Colleagues"],
  "Sports Events / Tournaments": [
    "Sports Fans",
    "Athletes & Players",
    "Youth Groups",
    "Schools & Clubs",
    "General Public",
  ],
  "Marathons / Fitness Events": [
    "Fitness Enthusiasts",
    "Athletes",
    "General Public",
    "Health-Conscious Adults",
    "Youth Groups",
  ],
  "Outdoor Adventures": [
    "Adventure Seekers",
    "Tourists & Expats",
    "Youth Groups",
    "Fitness Enthusiasts",
  ],
  "Charity Events": [
    "Donors & Sponsors",
    "Community Members",
    "NGOs & Volunteers",
    "Corporate Partners",
    "General Public",
  ],
  "Religious Events": [
    "Religious Communities",
    "Families",
    "General Public",
    "Devotees & Worshippers",
  ],
  "Community Gatherings": [
    "Local Community",
    "Families",
    "General Public",
    "Community Leaders",
  ],
  "Exhibitions / Trade Shows": [
    "Businesses & SMEs",
    "Investors",
    "Customers & Consumers",
    "Industry Professionals",
    "Media & Press",
  ],
  "Private Events": [
    "Invited Guests",
    "VIP Attendees",
    "Close Friends & Family",
  ],
  Other: ["General Audience", "General Public", "Custom Audience"],
};

export const EVENT_CATEGORIES = [
  "Music Concerts",
  "Festivals & Cultural Events",
  "DJ / Club Events",
  "Live Performances / Shows",
  "Conferences",
  "Seminars / Workshops",
  "Product Launches",
  "Corporate Events / Meetings",
  "University Events",
  "Hackathons / Competitions",
  "Training Sessions",
  "Weddings",
  "Birthday Parties",
  "Anniversaries",
  "Reunions",
  "Sports Events / Tournaments",
  "Marathons / Fitness Events",
  "Outdoor Adventures",
  "Charity Events",
  "Religious Events",
  "Community Gatherings",
  "Exhibitions / Trade Shows",
  "Private Events",
  "Other",
];
